### ISSUE TITLE
Register new user

### ISSUE THREAD

**Issue by samanyougarg** [jsoetens/flask-oauth2-boilerplate#1]
Hi!

Thanks for developing such a useful boilerplate.

I was wondering why there is no "sign up" option in the boilerplate. How will a new user register without Google/Facebook login?

Thanks

**Comment by jsoetens** [comment]
Thank you, glad you like the boilerplate. The whole idea was basically to focus only on OAuth 2.0 authorization, which I consider to be much more convenient and safer. For testing I also implemented some users with Argon2 password hashing. I will keep your request open and when I have some time add registration and password reset.
